= rabbit-jms-boot-demo

This sample application demonstrates the http://blog.gopivotal.com/products/messaging-with-jms-and-rabbitmq[Rabbit JMS connector] by producing and consuming stock quotes.

To use it, you need to have RabbitMQ http://www.rabbitmq.com/download.html[installed] and running.

Assuming you have this up in one of your terminal windows (something like):

[source]
----
$ rabbitmq-server

              RabbitMQ *.*.*. Copyright (C) 2007-2015 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: /usr/local/var/log/rabbitmq/rabbit@localhost.log
  ######  ##        /usr/local/var/log/rabbitmq/rabbit@localhost-sasl.log
  ##########
              Starting broker... completed with 6 plugins.
----

…you are now ready to proceed!

== Getting started…fast!

One of the fastest ways to get this demo going is using https://github.com/spring-projects/spring-boot/tree/master/spring-boot-cli[Spring Boot's CLI]. That link will show you how to install it using multiple options (homebrew, gvm, …).

With Spring Boot, just try this.

[source]
----
$ spring run consumer.groovy producer.groovy
----

It might take a minute or two to download some dependencies if this is the first time you've used Spring Boot. But after that, you should see something like this:

[source]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.1.RELEASE)

2016-01-15 12:11:36.331  INFO 12834 --- [       runner-0] o.s.boot.SpringApplication               : Starting application on retina with PID 12834 (/Users/gturnquist/.m2/repository/org/springframework/boot/spring-boot/1.3.1.RELEASE/spring-boot-1.3.1.RELEASE.jar started by gturnquist in /Users/gturnquist/src/rabbit-jms-boot-demo)
2016-01-15 12:11:36.333  INFO 12834 --- [       runner-0] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2016-01-15 12:11:36.370  INFO 12834 --- [       runner-0] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4964936e: startup date [Fri Jan 15 12:11:36 CST 2016]; root of context hierarchy
2016-01-15 12:11:36.856  INFO 12834 --- [       runner-0] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'connectionFactory' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=stockConsumer; factoryMethodName=connectionFactory; initMethodName=null; destroyMethodName=(inferred); defined in com.rabbitmq.jms.sample.StockConsumer] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=stockQuoter; factoryMethodName=connectionFactory; initMethodName=null; destroyMethodName=(inferred); defined in com.rabbitmq.jms.sample.StockQuoter]
2016-01-15 12:11:37.165  INFO 12834 --- [       runner-0] com.rabbitmq.jms.sample.StockConsumer    : connectionFactory => RMQConnectionFactory{user='guest', password=xxxxxxxx, host='localhost', port=5672, virtualHost='/', queueBrowserReadMax=0}
2016-01-15 12:11:37.329  INFO 12834 --- [       runner-0] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-01-15 12:11:37.334  INFO 12834 --- [       runner-0] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2016-01-15 12:11:37.406  INFO 12834 --- [       runner-0] o.s.boot.SpringApplication               : Started application in 1.228 seconds (JVM running for 3.805)
2016-01-15 12:11:37.468  INFO 12834 --- [pool-6-thread-1] com.rabbitmq.jms.sample.StockQuoter      : Quote...GD is now 83.27
2016-01-15 12:11:37.515  INFO 12834 --- [  jmsListener-1] com.rabbitmq.jms.sample.Receiver         : Received tip Quote...GD is now 83.27
2016-01-15 12:11:42.404  INFO 12834 --- [pool-6-thread-1] com.rabbitmq.jms.sample.StockQuoter      : Quote...GD is now 77.44
2016-01-15 12:11:42.490  INFO 12834 --- [  jmsListener-1] com.rabbitmq.jms.sample.Receiver         : Received tip Quote...GD is now 77.44
----

In the midst of all that output, you should notice this:

[source]
----
2016-01-15 12:11:37.165  INFO 12834 --- [       runner-0] com.rabbitmq.jms.sample.StockConsumer    : connectionFactory => RMQConnectionFactory{user='guest', password=xxxxxxxx, host='localhost', port=5672, virtualHost='/', queueBrowserReadMax=0}
----

This demonstrations that the connection factory is `RMQConnectionFactory`, the key piece of the Rabbit JMS project.

== Moving to big time production

Okay, that was neat. With less than 100 lines of Groovy code, you saw a nice demo of production/consumption through JMS. But perhaps you need something a little more scalable for a big application. For starters, that Groovy application up above requires access to the Internet and also contains the super secret location of the Rabbit JMS client. These would be key reasons you can't just hand the code to anyone.

So…how about building a deliverable artifact using Maven? Here we have a demonstration of using this code in pure Java.

[source]
----
$ mvn clean spring-boot:run
----

This will use Maven to build and launch the application as well.

[source]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.1.RELEASE)

2016-01-15 12:13:36.470  INFO 13086 --- [           main] com.rabbitmq.jms.sample.StockQuoter      : Starting StockQuoter on retina with PID 13086 (/Users/gturnquist/src/rabbit-jms-boot-demo/target/classes started by gturnquist in /Users/gturnquist/src/rabbit-jms-boot-demo)
2016-01-15 12:13:36.473  INFO 13086 --- [           main] com.rabbitmq.jms.sample.StockQuoter      : No active profile set, falling back to default profiles: default
2016-01-15 12:13:36.511  INFO 13086 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6e8d04b7: startup date [Fri Jan 15 12:13:36 CST 2016]; root of context hierarchy
2016-01-15 12:13:37.160  INFO 13086 --- [           main] com.rabbitmq.jms.sample.StockConsumer    : connectionFactory => RMQConnectionFactory{user='guest', password=xxxxxxxx, host='localhost', port=5672, virtualHost='/', queueBrowserReadMax=0}
2016-01-15 12:13:37.748  INFO 13086 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-01-15 12:13:37.753  INFO 13086 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2016-01-15 12:13:37.801  INFO 13086 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2016-01-15 12:13:37.885  INFO 13086 --- [pool-4-thread-1] com.rabbitmq.jms.sample.StockQuoter      : Quote...AAPL is now 529.0
2016-01-15 12:13:37.887  INFO 13086 --- [           main] com.rabbitmq.jms.sample.StockQuoter      : Started StockQuoter in 1.584 seconds (JVM running for 4.293)
2016-01-15 12:13:38.005  INFO 13086 --- [  jmsListener-1] com.rabbitmq.jms.sample.StockConsumer    : Received Quote...AAPL is now 529.0
2016-01-15 12:13:42.888  INFO 13086 --- [pool-4-thread-1] com.rabbitmq.jms.sample.StockQuoter      : Quote...GD is now 88.0
2016-01-15 12:13:42.959  INFO 13086 --- [  jmsListener-1] com.rabbitmq.jms.sample.StockConsumer    : Received Quote...GD is now 88.0
----

Pretty much the same stuff.

Finally, you can build a releasable JAR file.

[source]
----
$ mvn clean package
----

This creates a JAR file that you can hand out as well as run from the command line.

[source]
----
$ java -jar target/rabbit-jms-boot-demo-1.0.0-SNAPSHOT.jar
----

As you can see, the JAR file is runnable.

[source]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v1.3.1.RELEASE)

2013-10-25 09:37:57.838  ... com.rabbitmq.jms.sample.StockQuoter      : Starting StockQuoter on retina with PID 69317 (/Users/gturnquist/src/rabbit-jms-boot-demo/target/rabbit-jms-boot-demo-1.0.3-SNAPSHOT.jar started by gturnquist)
…
----

This means you can load it up in your favorite IDE, open up `StockQuoter`, and look for this:

[source,java]
----
public static void main(String[] args) {
	SpringApplication.run(StockQuoter.class, args);
}
----

That is a plain ole *`public static void main`*, which you can run in debug mode inside your IDE with check points in order to see what's going on.

Happy coding!

== Version issues

This code is using Rabbit JMS Client development level. We should use a production version.

The project's parent dependency is *`spring-boot-starter-parent`*. That lets it pull in default versions of things like Spring JMS without having to spec the versions by leaning on Spring Boot's choices.

[source,xml]
----
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.3.1.RELEASE</version>
</parent>
----

But it mandates a specific `rabbit-jms` client version:

[source,xml]
----
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.rabbitmq.jms</groupId>
			<artifactId>rabbitmq-jms</artifactId>
			<version>${rabbitmq-jms.version}</version>
		</dependency>
	</dependencies>
</dependencyManagement>
----

where the property `rabbitmq-jms.version` is set in a properties section.

== Help

If you need help, contact either Steve Powell or Greg Turnquist for questions.